### ISSUE TITLE
Provide example for configuring a Kubernetes pool

### ISSUE THREAD

**Issue by abatilo** [mailgun/groupcache#19]
It's mentioned [here](https://www.mailgun.com/blog/golangs-superior-cache-solution-memcached-redis/) that you could use Kubernetes as a discovery mechanism, but then the example links to a different mailgun project.

It would be nice if there was an example for how to use Kubernetes while integrated with groupcache, not gubernator.

**Comment by nvcnvn** [comment]
Kind of out of the topics, but do we have documentation about behavior to handle peer unexpected shutdown?
How to "discover" that you may need to update peers list when having new k8s deployment?

**Comment by thrawn01** [comment]
This is a bit out of scope for this project as kubernetes is a moving target. But if you want a working example of how to get a list of services to update the pool. Gubernator has such an example https://github.com/mailgun/gubernator/blob/master/kubernetes.go There are other resources available on the internet for discovering peers in your chosen environment.
