### ISSUE TITLE
Support to Attach to Already Running Server

### ISSUE THREAD

**Issue by bkannadassan** [mailgun/groupcache#26]
Hi,

There is already a http server running on a port xxxxx. Is it possible to attach groupcache to the same ?. I see that its sending a request  "http://_groupcache/<groupName>/<id string>". Should we handle this and call the groupcache get in each node ?. I hope this wouldn't go in a loop. Any help on the same is much appreciated..

rgds
Baljai Kamal Kannadassan

**Comment by thrawn01** [comment]
Group cache already can dynamically add or remove peers via the `pool.Set()` call. It's up to you to hook into a service discovery mechanism to know when other instances of groupcache need to join the consistent hash ring.
