### ISSUE TITLE
Deadlock in groupcache lookup

### ISSUE THREAD

**Issue by workhorse2020** [mailgun/groupcache#27]
```
func main() {
                pool := groupcache.NewHTTPPoolOpts("http://x.x.x.x:8380", &groupcache.HTTPPoolOptions{})
                pool.Set("http://y.y.y.y:8280")
                server := http.Server{
                        Addr:    "localhost:8380",
                        Handler: pool,
                }
                go func() {
```
When give the sameway to the other people y.y.y.y poolset as x.x.x.x it goes into a deadlock and looking up the db if entry not found. If in y.y.y.y  I don;t give Set as x.x.x.x things works fine. 

Hence precisely

A-> B
B-> A

Above is not valid and we should make sure it doesn't happen this way ?. I mean circular loop ?.

rgds
Kamal

**Comment by thrawn01** [comment]
Should include self when setting the pool. 
```golang
pool.Set("http://y.y.y.y:8280", "http://x.x.x.x:8380")
```

**Comment by taraspos** [comment]
@thrawn01 I guess the main example from readme has to be update, because there, self is not being added to the pool:

```go
    // Keep track of peers in our cluster and add our instance to the pool `http://localhost:8080`
    pool := groupcache.NewHTTPPoolOpts("http://localhost:8080", &groupcache.HTTPPoolOptions{})

    // Add more peers to the cluster
    pool.Set("http://peer1:8080", "http://peer2:8080")
```

**Comment by thrawn01** [comment]
@Trane9991 done!
